# Generated by Django 5.1.2 on 2024-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnortAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_message', models.CharField(max_length=255)),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
    ]
